# Generated by Django 5.1.6 on 2025-02-15 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome_title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('prerequisite_title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
            ],
        ),
    ]
