# Generated by Django 5.1.6 on 2025-02-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_title', models.CharField(max_length=255)),
                ('resource_link', models.URLField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson')),
            ],
        ),
    ]
