name: Deploy Django Backend to cPanel

on:
  push:
    branches:
      - main  # Change this if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to cPanel via Git
        uses: pinkasey/cpanel-repository-action@v1.2.0
        with:
          hostname: ${{ secrets.CPANEL_HOSTNAME }}
          cPanelApiPort: 2083
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          repository_root: /home/bigmoqks/repositories/academyBackend  # Ensure this path is correct
          branch: main  # Ensure this matches your GitHub branch
          timeout: 300000  # 5-minute timeout

      - name: SSH into cPanel and Restart Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.CPANEL_HOSTNAME }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}  # Secure SSH Key
          script: |
            # Activate virtual environment
            source /home/bigmoqks/virtualenv/academyBackend/3.10/bin/activate

            # Navigate to project directory
            cd /home/bigmoqks/academyBackend

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Apply database migrations
            python manage.py migrate --noinput

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart server (touch restart.txt for Passenger-based servers)
            touch tmp/restart.txt

            # Ensure correct file permissions
            chmod -R 755 /home/bigmoqks/academyBackend
