name: Deploy Django to cPanel

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key bigmoqks@your-cpanel-ip "echo SSH Connected"

    - name: Trigger Deployment Script on cPanel
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key bigmoqks@your-cpanel-ip << 'EOF'
        cd /home/bigmoqks/academyBackend
        git pull origin main
        source /home/bigmoqks/virtualenv/academyBackend/3.10/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        touch /home/bigmoqks/academyBackend/tmp/restart.txt
        EOF
